name: Makefile CI

on:
  push:
    branches: [ "extra" ]
  pull_request:
    branches: [ "extra" ]

jobs:
  build:

#     runs-on: ubuntu-latest
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
  
    - name: install mxe requirements
      run: |
            sudo apt update
            sudo apt install -y \
            autoconf \
            automake \
            autopoint \
            bash \
            bison \
            bzip2 \
            flex \
            g++ \
            gettext \
            git \
            gperf \
            intltool \
            libgdk-pixbuf2.0-dev \
            libltdl-dev \
            libgl-dev \
            libssl-dev \
            libtool-bin \
            libxml-parser-perl \
            lzip \
            make \
            openssl \
            p7zip-full \
            patch \
            perl \
            python3 \
            python3-mako \
            python3-pkg-resources \
            ruby \
            sed \
            unzip \
            wget \
            xz-utils
            sudo apt-get install \
            software-properties-common \
            lsb-release
            sudo apt-key adv \
                --keyserver keyserver.ubuntu.com \
                --recv-keys 86B72ED9 && \
            sudo add-apt-repository \
                "deb [arch=amd64] https://pkg.mxe.cc/repos/apt `lsb_release -sc` main" && \
            sudo apt-get update
            sudo apt-get install -y \
            mxe-x86-64-w64-mingw32.static-cc \
            mxe-x86-64-w64-mingw32.static-djvulibre \
            mxe-x86-64-w64-mingw32.static-libspectre \
            mxe-x86-64-w64-mingw32.static-qtsvg \
            mxe-x86-64-w64-mingw32.static-qttools \
            mxe-x86-64-w64-mingw32.static-poppler

    - name: install mxe
      run: |
           suo cp qpdfview.mk /usr/lib/mxe/plugins/apps
           cd /usr/lib/mxe
           sudo make JOBS=4 qpdfview MXE_TARGETS="x86_64-w64-mingw32.static" MXE_PLUGIN_DIRS+=plugins/apps

#     - name: Run check
#       run: make check

#     - name: Run distcheck
#       run: make distcheck
