name: Makefile CI

on:
  push:
    branches: [ "extra" ]
  pull_request:
    branches: [ "extra" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: install mxe requirements
      run: |
            sudo apt update
            sudo apt install -y \
            autoconf \
            automake \
            autopoint \
            bash \
            bison \
            bzip2 \
            flex \
            g++ \
            g++-multilib \
            gettext \
            git \
            gperf \
            intltool \
            libc6-dev-i386 \
            libgdk-pixbuf2.0-dev \
            libltdl-dev \
            libgl-dev \
            libssl-dev \
            libtool-bin \
            libxml-parser-perl \
            lzip \
            make \
            openssl \
            p7zip-full \
            patch \
            perl \
            python3 \
            python3-mako \
            python3-pkg-resources \
            ruby \
            sed \
            unzip \
            wget \
            xz-utils \
            g++-multilib \
            libc6-dev-i386

    - name: install mxe
      run: |
           git clone https://github.com/mxe/mxe
           cp qpdfview.mk mxe/plugins/apps
           cd mxe
           make JOBS=4 qpdfview MXE_TARGETS="i686-w64-mingw32.static x86_64-w64-mingw32.static" MXE_PLUGIN_DIRS+=plugins/apps

#     - name: Run check
#       run: make check

#     - name: Run distcheck
#       run: make distcheck
